[[responses]]

[responses.RandomText]
name = "rust"
pattern = "rust"
content = [
    "RUST MENTIONED :crab: :crab: :crab:",
    "<@216767618923757568>",
    "Rust is simply the best programming language. Nothing else can compare. I am naming my kids Rust and Ferris.",
    """
    Launch the Polaris,
    the end doesn't scare us
    When will this cease?
    The warheads will all rust in peace
    """,
    "Rust? Oh, you mean the game?"
]

[[responses]]

[responses.TextAndImage]
name = "tkinter"
pattern = "tkinter"
content = "TKINTER MENTIONED"
path = "./assets/tkinter.png"

[[responses]]

[responses.Text]
name = "arch"
pattern = "arch"
content = "I use Arch btw."

[[responses]]

[responses.RandomText]
name = "goop"
pattern = "goop"
content = [
    "https://tenor.com/view/gunge-gunged-slime-slimed-dunk-gif-21115557",
    "https://tenor.com/view/goop-goop-house-jello-gif-23114313"
]

[[responses]]

[responses.Text]
name = "1984"
pattern = "1984"
content = "https://tenor.com/view/1984-gif-19260546"

[[responses]]

[responses.Text]
name = "cs major"
pattern = 'cs\s*major'
content = "I don't get the way you guys think. I want MONEY. 6 figures out of college. 200k a year entry level. I'm in this for MONEY. I don't care about whether I'm \"fulfilled\" I want MONEY. Whatever gets me the most MONEY. What technology gets me PAID THE BEST. All I care about in this major is MONEY. That's why I'm in college, I don't wanna laugh and play with y'all. I don't wanna be buddy buddy with y'all. I'm here for MONEY."
